name: Docker Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: docker build -t computacion18-05-tests .

      - name: Ejecutar tests dentro del contenedor
        run: docker run --rm computacion18-05-tests
